### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by MrCalhoun** [exane/not-gwent-online#1]
Hey there,

I setup a new ubuntu x64 machine and installed:

nodejs
npm
graphicsmagick
xampp
(and openssh-server)

After I cloned your repository and changed to the folder I ran "npm install" and get the following output
How to solve that problem?

**Comment by exane** [comment]
It seems like you're using an old version of node. (v0.10.25)
Try updating your version to a newer one (like v4.2.4) and run npm install again.

**Comment by MrCalhoun** [comment]
That was the issue. I installed v5 and it worked now.
But "node server/server.js" seems to be stuck. I doesn't do anything since 5 minutes.

**Comment by exane** [comment]
Yeah thats the server listening for user input and has to be kept alive. If you now open your client in your webbrowser you will see that the server responds if someone connects.

**Comment by MrCalhoun** [comment]
nevermind. It works for me now. My VM got not many ressouces^^
Thanks for the project! I will write later an automatic installation script :)

**Comment by exane** [comment]
Alright, glad you got it working. Appreciate your commitment!
