### ISSUE TITLE
do not load the images of the cards

### ISSUE THREAD

**Issue by SrGalletaEXT** [exane/not-gwent-online#6]
Hello!! first sorry for my English is bad XD. My problem is that loads all-inclusive music except the images of the cards, their silhouettes are but fail to load. I've tried everything but that does not fail. Everything is installed, to run perfectly build ect .. Any ideas?

**Comment by dobroliubov** [comment]
Just check the location of /assets/ folder. It's not under the /public. So, you should configure your webserver to forward all requests to appropriate place. For example, for nginx:
            location / {
                root /usr/local/www/gwent/public;
                index index.html;
            }
            location /assets/ {
                root /usr/local/www/gwent;
            }
            location /public/ {
                root /usr/local/www/gwent;
            }

**Comment by arojasq** [comment]
So I set up everything and it works (loads, connects with other people, etc.) but I can't see the cards. 

Noticed the browser is looking for a .css file that doesn't exist:

Failed to load resource: the server responded with a status of 404 (Not Found) - http://<host>:<port>/**build/cards.css** 

Any thoughts on that? Should I have to rebuild ?

**Comment by KetchupBomb** [comment]
@arojasq

`public/build/cards.PNG` is incorrectly named -- it's actually a CSS file. Move/copy it and reload your browser, images will then load.

`cp public/build/cards.PNG public/build/cards.css`
