### ISSUE TITLE
Is it possible to make it accessible from outside LAN?

### ISSUE THREAD

**Issue by MJShadowsky** [exane/not-gwent-online#8]
Hi,

To introduce myself, I'm completely new to NodeJS and Socket.IO - I've looked into it just now because of this game ;)

My story:
I've installed the Node server, GM and installed/built the game package (as per your instructions) on my PC. I've also had to install express, socket.ie and socket.io-client beforehand so the installation/build didn't return any errors.
It works fine inside LAN.
I've also managed to access the server and load the game page from outside by my public IP.

The problem is that the devices outside of LAN don't connect via Socket.IO - therefore, for them, the game server stays Offline.

I've edited Config.js & Server.js by changing hostname IPs and Ports as well as trying different solutions for Socket.IO I've found online, without luck.

I've tested Node & Socket.IO on my PC with a few simple apps and that did work.

What can be wrong here? Please help :)

**Comment by Facottons** [comment]
Hi bro. These're the words from the author from "https://www.reddit.com/r/witcher/comments/3c4tfq/gwentonlinecom_a_standalone_multiplayer_version/":

 "Gwent-online is down!

We are so sorry guys. But we have to cut here.

We are not allowed to host gwent-online and we are forced to take it down.
All I have left to say is:

You guys are awesome! There was so much feedback, critics and commitment. It was only for a weekend, but we are quite happy. We have never expected so much activity. At peak times there were 500+ people online. Crazy!

Thanks to everyone! We read every post and wrote each issue down but we are done now. "

So, if you wanna play with your friends, I strongly recommend you try out a tool called "lan bridger" http://www.lanbridger.com/ . It simulates that you and your friends are part of the same local computer network.

Hope it works for you!

Facottons

**Comment by MJShadowsky** [comment]
Thanks a lot for your reply and for the advice.
