### ISSUE TITLE
Detailed tutorial?

### ISSUE THREAD

**Issue by mfskiryu** [exane/not-gwent-online#9]
I have no idea what the instructions mean besides the installing of the software needed. Any help would be appreciated.

**Comment by WittyWolf2309** [comment]
Hey. :)
I'm a newb like you, but with a little help from a friend I was able to figure it out quite easily.
I'll can give you detailed instructions if you want, but I need to ask, 
Are you a Windows user or a Mac user?

**Comment by mfskiryu** [comment]
Thanks and I'm on Windows.

**Comment by WittyWolf2309** [comment]
Okay. That's good. 
Start by installing node. 
Then you need to INSTALL GraphicsMagick. There's a dll file for it, like a setup. About 5mbs. You'll have to track that down yourself. If you can't I'll help you get it. 
Okay. Here's a the technical bits. 
Copy the not-gwent-online-master folder into your OS directory, anywhere. 
Press Ctrl+Shift+Esc to open the Task Manager. Go to file, click on run. 
Type "cmd".  And check the "Run this with administrator privileges" option. 
You should now be in command prompt. 
Type:
Cd (path for wherever you put the gwent folder) 
Example: Cd C:\Project Gwent\not-gwent-online-master 
Now that you're in the directory, type :
Npm install 
Let it do its thing. 
When the process is complete, open the gwent folder, find the config file  file and edit the IP address to your LOCAL IP ADDRESS. 
Next, go back to command prompt, and type:
Npm run build
After the build is running 
Type 
Node server/server.js 
That will start the server. 
Open Firefox. Enter your local IP and add :3000 in front of it. 
Ex: 192.168.0.20:3000 
That's it. It should work now.

**Comment by WittyWolf2309** [comment]
Repeat the process on a another laptop, except for the node server/server.js command. 
Make sure you're on the same local network. Then have your friend enter the same IP address that you're playing gwent on. You'll be connected.

**Comment by mfskiryu** [comment]
I love you, thank you so much.
